---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.vetch.io
  resources:
  - virtualinferenceclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.vetch.io
  resources:
  - virtualinferenceclusters/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.vetch.io
  resources:
  - virtualinferenceclusters/status
  verbs:
  - get
  - patch
  - update
